language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - git config --global url."https://".insteadOf git://
  - 'bower install'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fbe67f6a1735604862c6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false